default[:ce_front_end][:repository] = "https://github.com/pghalliday/ce-front-end.git"
default[:ce_front_end][:destination] = "/opt/ce-front-end"
default[:ce_front_end][:user] = "ce-front-end"
default[:ce_front_end][:port] = "3000"
default[:ce_front_end][:commission][:account] = "commission"
default[:ce_front_end][:ce_operation_hub][:host] = "localhost"
default[:ce_front_end][:ce_operation_hub][:submit] = "4000"
default[:ce_front_end][:ce_delta_hub][:host] = "localhost"
default[:ce_front_end][:ce_delta_hub][:stream] = "5000"
default[:ce_front_end][:ce_delta_hub][:state] = "5001"

# dependency defaults
default[:nodejs][:install_method] = "package"
default[:git][:version] = "1.8.3"
default[:zeromq][:version] = "3.2.3"
default[:zeromq][:url] = "http://download.zeromq.org"
